name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest requests sqlalchemy

      - name: Start FastAPI Server
        run: |
          uvicorn apiserver:app --host 127.0.0.1 --port 8000 &  
          sleep 3  # Wait for the server to start

      - name: Run Tests
        run: pytest testAutomation.py -v
